Add if statement

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -39,6 +39,11 @@ jobs:
           for i in $(seq 1 12); do sleep 10 && docker logs test; done
           curl --fail http://localhost:25565
           docker stop test
+          if [docker container inspect -f "{{.State.Health.Status}}" test != "healthy"]; then
+            echo "Smoke test failed"
+            exit 1
+          fi
+            echo "Smoke test passed"
 
       - name: Tag and push to ECR
         env:
